export const data = [
  {
    id: 1,
    title: "Grandson of Tunday",
    icon: "/Images/biryani-10.jpeg",
    cusineType: "biryani",
    Ratings: 4.0,
    offer: "60% OFF",
    deliveryTime: "39 min",
    price: 100,
    cusineNameAndlocattion: "Ambur biryani ",
    catagory: "biryani",
  },
  {
    id: 2,
    title: "Idris Ki , Lucknow",
    icon: "./Images/biryani-2.jpeg",
    cusineType: "biryani",
    Ratings: 4.3,
    offer: "46% OFF",
    deliveryTime: "30 min",
    price: 110,
    cusineNameAndlocattion: " chicken Biryani",
    catagory: "biryani",
  },
  {
    id: 3,
    title: "Jaffer ,Mumbai",
    icon: "./Images/biryani-3.jpeg",
    cusineType: "biryani",
    Ratings: 3.9,
    offer: "RS.35 OFF",
    deliveryTime: "20 min",
    price: 130,
    cusineNameAndlocattion: "Panner dum Biryani",
    catagory: "biryani",
  },
  {
    id: 4,
    title: "Soya keema ",
    icon: "./Images/biryani-4.jpeg",
    cusineType: "biryani",
    Ratings: 3.0,
    offer: "10% OFF",
    deliveryTime: "39 min",
    price: 100,
    cusineNameAndlocattion: " Bawarchi, Hyderabad",
    catagory: "biryani",
  },
  {
    id: 5,
    title: "Paneer Biryani",
    icon: "./Images/biryani-5.jpeg",
    cusineType: "biryani",
    Ratings: 4.9,
    offer: "75% OFF",
    deliveryTime: "29 min",
    price: 100,
    cusineNameAndlocattion: "Oudh 1590, Kolkata",
    catagory: "biryani",
  },
  {
    id: 6,
    title: "Soya chunks ",
    icon: "./Images/biryani-6.jpeg",
    cusineType: "biryani",
    Ratings: 4.6,
    offer: "23% OFF",
    deliveryTime: "30 min",
    price: 120,
    cusineNameAndlocattion: "Sukkubhai , Chennai",
    catagory: "biryani",
  },
  {
    id: 7,
    title: "Prawn Biryani",
    icon: "./Images/biryani-7.jpeg",
    cusineType: "biryani",
    Ratings: 3.6,
    offer: "17% OFF",
    deliveryTime: "10 min",
    price: 130,
    cusineNameAndlocattion: " Al- Jawahar, Delhi",
    catagory: "biryani",
  },
  {
    id: 8,
    title: "Muslim Biryani",
    icon: "./Images/biryani-8.jpeg",
    cusineType: "biryani",
    Ratings: 3.4,
    offer: "Rs.50 OFF",
    deliveryTime: "25 min",
    price: 100,
    cusineNameAndlocattion: "Wahid, Lucknow",
    catagory: "biryani",
  },
  {
    id: 9,
    title: "Plain Biryani",
    icon: "./Images/biryani-9.jpeg",
    cusineType: "biryani",
    Ratings: 3.2,
    offer: "60% OFF",
    deliveryTime: "39 min",
    price: 100,
    cusineNameAndlocattion: "Bawarchi, Hyderabad",
    catagory: "biryani",
  },
  {
    id: 10,
    title: "Cicken fry Biryani",
    icon: "./Images/biryani-10.jpeg",
    cusineType: "biryani",
    Ratings: 3.0,
    offer: "13% OFF",
    deliveryTime: "20 min",
    price: 100,
    cusineNameAndlocattion: " Al- Jawahar, Delhi",
    catagory: "biryani",
  },
  {
    id: 11,
    title: "Ambur Biryani",
    icon: "./Images/biryani-11.jpeg",
    cusineType: "biryani",
    Ratings: 3.3,
    offer: "34% OFF",
    deliveryTime: "25 min",
    price: 100,
    cusineNameAndlocattion: "Shadab, Hyderabad",
    catagory: "biryani",
  },
  {
    id: 12,
    title: "Thalassery Biryani",
    icon: "./Images/biryani-12.jpeg",
    cusineType: "biryani",
    Ratings: 4.0,
    offer: "19% OFF",
    deliveryTime: "27 min",
    price: 120,
    cusineNameAndlocattion: "Shadab, Hyderabad",
    catagory: "biryani",
  },
  {
    id: 13,
    title: "Malabar Biryani",
    icon: "./Images/biryani-13.jpeg",
    cusineType: "biryani",
    Ratings: 3.4,
    offer: "56% OFF",
    deliveryTime: "17 min",
    price: 100,
    cusineNameAndlocattion: " Noor Mohammadi , Mumbai",
    catagory: "biryani",
  },
  {
    id: 14,
    title: "Awadhi Biryani",
    icon: "./Images/biryani-14.jpeg",
    cusineType: "biryani",
    Ratings: 4.4,
    offer: "13% OFF",
    deliveryTime: "33 min",
    price: 100,
    cusineNameAndlocattion: "Kfc,Chennai",
    catagory: "biryani",
  },
  {
    id: 15,
    title: "Hyderabadi Biryani",
    icon: "./Images/biryani-15.jpeg",
    cusineType: "biryani",
    Ratings: 3.2,
    offer: "Rs.40 OFF",
    deliveryTime: "29 min",
    price: 100,
    cusineNameAndlocattion: "Kfc,andhra",
    catagory: "biryani",
  },
  {
    id: 16,
    title: "Chettinad Biryani",
    icon: "./Images/biryani-16.jpeg",
    cusineType: "biryani",
    Ratings: 3.8,
    offer: "13% OFF",
    deliveryTime: "20 min",
    price: 100,
    cusineNameAndlocattion: "Maplai, Chennai",
    catagory: "biryani",
  },
  {
    id: 17,
    title: "Chicken Biryani",
    icon: "./Images/biryani-17.jpeg",
    cusineType: "biryani",
    Ratings: 3.9,
    offer: "33% OFF",
    deliveryTime: "39 min",
    price: 100,
    cusineNameAndlocattion: "Kfc,delhi",
    catagory: "biryani",
  },
  {
    id: 18,
    title: " LACADOR",
    icon: "./Images/burger-1.jpeg",
    cusineType: "burger",
    Ratings: 4.7,
    offer: "46% OFF",
    deliveryTime: "20 min",
    price: 140,
    cusineNameAndlocattion: "Kfc,mumbai",
    catagory: "burger",
  },
  {
    id: 19,
    title: "FRITZ",
    icon: "./Images/burger-2.jpeg",
    cusineType: "burger",
    Ratings: 3.7,
    offer: "13% OFF",
    deliveryTime: "20 min",
    price: 100,
    cusineNameAndlocattion: "Maplai, Chennai",
    catagory: "burger",
  },
  {
    id: 20,
    title: "GRINGO",
    icon: "./Images//burger-3.jpeg",
    cusineType: "burger",
    Ratings: 3.0,
    offer: "47% OFF",
    deliveryTime: "36 min",
    price: 100,
    cusineNameAndlocattion: "Kfc,bangalore",
    catagory: "burger",
  },
  {
    id: 21,
    title: "PAMPA BURGER",
    icon: "./Images/burger-4.jpeg",
    cusineType: "burger",
    Ratings: 2.0,
    offer: "23% OFF",
    deliveryTime: "43 min",
    price: 100,
    cusineNameAndlocattion: "Dominos,chennai",
    catagory: "burger",
  },
  {
    id: 22,
    title: "CHIMANGO",
    icon: "./Images/burger-5.jpeg",
    cusineType: "burger",
    Ratings: 4.3,
    offer: "10% OFF",
    deliveryTime: "20 min",
    price: 90,
    cusineNameAndlocattion: "pizza Hurt,tambaram",
    catagory: "burger",
  },
  {
    id: 23,
    title: "PIRATINI",
    icon: "./Images/burger-7.jpeg",
    cusineType: "burger",
    Ratings: 4.4,
    offer: "13% OFF",
    deliveryTime: "22 min",
    price: 100,
    cusineNameAndlocattion: "Maplai, Chennai",
    catagory: "burger",
  },
  {
    id: 24,
    title: " Taco burger",
    icon: "./Images/burger-7.jpeg",
    cusineType: "burger",
    Ratings: 4.9,
    offer: "5% OFF",
    deliveryTime: "20 min",
    price: 100,
    cusineNameAndlocattion: "Burger King,chennai",
    catagory: "burger",
  },
  {
    id: 25,
    title: "LA PLATA",
    icon: "./Images/burger-8.jpeg",
    cusineType: "burger",
    Ratings: 4.0,
    offer: "23% OFF",
    deliveryTime: "10 min",
    price: 100,
    cusineNameAndlocattion: "Fasos,chennai",
    catagory: "burger",
  },
  {
    id: 26,
    title: " Hot Dog burger",
    icon: "./Images/burger-9.jpeg",
    cusineType: "burger",
    Ratings: 4.4,
    offer: "45% OFF",
    deliveryTime: "36 min",
    price: 100,
    cusineNameAndlocattion: "Maplai, Chennai",
    catagory: "burger",
  },
  {
    id: 27,
    title: "Cheesel burger",
    icon: "./Images/burger-10.jpeg",
    cusineType: "burger",
    Ratings: 4.3,
    offer: "36% OFF",
    deliveryTime: "29 min",
    price: 100,
    cusineNameAndlocattion: "Burger king,chittoor",
    catagory: "burger",
  },
  {
    id: 28,
    title: "Tranding This Week",
    info: "Most popular restaurants in town this week",
    icon: "./Images/biryani-10.jpeg",
    cusineType: "biryani",
    Ratings: 5.0,
    path: "Tranding",
    offer: "13% OFF",
    deliveryTime: "20 min",
    price: 100,
    cusineNameAndlocattion: "Kfc,oragadam",
    catagory: "collection",
  },
  {
    id: 29,
    title: "Best of Chennai",
    info: "The hunt of the height rated resturant in your city",
    icon: "./Images/biryani-16.jpeg",
    cusineType: "biryani",
    Ratings: 5.0,
    path: "Best_of_chennai",
    offer: "24% OFF",
    deliveryTime: "26 min",
    price: 100,
    cusineNameAndlocattion: "Maplai, Chennai",
    catagory: "collection",
  },
  {
    id: 30,
    title: "Late night delivery",
    info: " The perfect places to celebrate the ladies we love",
    icon: "./Images/biryani-14.jpeg",
    cusineType: "biryani",
    Ratings: 5.0,
    path: "Late_night_dinner",
    offer: "13% OFF",
    deliveryTime: "20 min",
    price: 100,
    cusineNameAndlocattion: " Fasos, Mumbai",
    catagory: "collection",
  },
  {
    id: 31,
    title: "Late night delivery",
    icon: "./Images/latenight.jpeg",
    cusineType: "biryani",
    Ratings: 4.9,
    path: "Late_night_dinner",
    offer: "13% OFF",
    deliveryTime: "20 min",
    price: 100,
    cusineNameAndlocattion: " Fasos, Mumbai",
    catagory: "late_night_delivery",
  },
  {
    id: 32,
    title: "Late night delivery",
    icon: "./Images/latenight_1.jpeg",
    cusineType: "biryani",
    Ratings: 4.1,
    path: "Late_night_dinner",
    offer: "13% OFF",
    deliveryTime: "20 min",
    price: 100,
    cusineNameAndlocattion: " Fasos, Mumbai",
    catagory: "late_night_delivery",
  },
  {
    id: 33,
    title: "Late night delivery",
    icon: "./Images/latenight_2.jpeg",
    cusineType: "biryani",
    Ratings: 4.1,
    path: "Late_night_dinner",
    offer: "13% OFF",
    deliveryTime: "20 min",
    price: 100,
    cusineNameAndlocattion: " Fasos, Mumbai",
    catagory: "late_night_delivery",
  },
  {
    id: 34,
    title: "Late night delivery",
    icon: "./Images/latenight_3.jpeg",
    cusineType: "biryani",
    Ratings: 4.1,
    path: "Late_night_dinner",
    offer: "13% OFF",
    deliveryTime: "20 min",
    price: 100,
    cusineNameAndlocattion: " Fasos, Mumbai",
    catagory: "late_night_delivery",
  },
  {
    id: 35,
    title: "Late night delivery",
    icon: "./Images/latenight_4.jpeg",
    cusineType: "biryani",
    Ratings: 3.3,
    path: "Late_night_dinner",
    offer: "13% OFF",
    deliveryTime: "20 min",
    price: 100,
    cusineNameAndlocattion: " Fasos, Mumbai",
    catagory: "late_night_delivery",
  },
  {
    id: 36,
    title: "Late night delivery",
    icon: "./Images/latenight_5.jpeg",
    cusineType: "biryani",
    Ratings: 4.1,
    path: "Late_night_dinner",
    offer: "13% OFF",
    deliveryTime: "20 min",
    price: 100,
    cusineNameAndlocattion: " Fasos, Mumbai",
    catagory: "late_night_delivery",
  },
  {
    id: 37,
    title: "Late night delivery",
    icon: "./Images/latenight_6.jpeg",
    cusineType: "biryani",
    Ratings: 4.1,
    path: "Late_night_dinner",
    offer: "13% OFF",
    deliveryTime: "20 min",
    price: 100,
    cusineNameAndlocattion: " Fasos, Mumbai",
    catagory: "late_night_delivery",
  },
  {
    id: 38,
    title: "Late night delivery",
    icon: "./Images/latenight_7.jpeg",
    cusineType: "biryani",
    Ratings: 3.5,
    path: "Late_night_dinner",
    offer: "13% OFF",
    deliveryTime: "20 min",
    price: 100,
    cusineNameAndlocattion: " Fasos, Mumbai",
    catagory: "late_night_delivery",
  },
];
export default data;
